import type { Metadata } from "next";
import "./globals.css";
import { CalendarProvider } from "../contexts/CalendarContext";

export const metadata: Metadata = {
  title: "Meraki",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CalendarProvider>{children}</CalendarProvider>
      </body>
    </html>
  );
}
