import { useState, useEffect, ReactNode } from "react";
import Image from "next/image";
import { formatTimeForDisplay, formatDateForDisplay } from "@/utils/dateUtils";

export interface Column<T> {
  key: string;
  header: string;
  render?: (item: T) => ReactNode;
  sortable?: boolean;
  centered?: boolean;
  mobileHidden?: boolean;
  type?: "text" | "date" | "time" | "image" | "badge" | "status" | "actions";
}

export interface FilterOption {
  key: string;
  label: string;
  options: { value: string; label: string }[];
  value: string;
  onChange: (value: string) => void;
  // Add support for custom filter logic
  customFilter?: (item: unknown, filterValue: string) => boolean;
}

interface DataTableProps<T> {
  data: T[];
  columns?: Column<T>[]; // Now optional
  autoColumns?: boolean; // Auto-generate columns from data
  excludeColumns?: string[]; // Columns to exclude from auto-generation
  searchable?: boolean;
  searchPlaceholder?: string;
  searchFields?: (keyof T)[];
  filters?: FilterOption[];
  onRowClick?: (item: T) => void;
  renderMobileCard?: (item: T) => ReactNode;
  itemsPerPageOptions?: number[];
  defaultItemsPerPage?: number;
  emptyMessage?: string;
  loading?: boolean;
  // Common render functions
  renderActions?: (item: T) => ReactNode;
  imageFields?: string[]; // Fields that should be rendered as images
  dateFields?: string[]; // Fields that should be formatted as dates
  timeFields?: string[]; // Fields that should be formatted as times
  statusFields?: string[]; // Fields that should be rendered as status badges
  // Add support for computed filters
  computedFilters?: {
    [key: string]: (item: T) => string | boolean | number;
  };
}

export default function DataTable<T extends object>({
  data,
  columns: providedColumns,
  autoColumns = true,
  excludeColumns = [],
  searchable = false,
  searchPlaceholder = "Search...",
  searchFields = [],
  filters = [],
  onRowClick,
  renderMobileCard,
  itemsPerPageOptions = [5, 10, 25, 50, 100],
  defaultItemsPerPage = 10,
  emptyMessage = "No data found.",
  loading = false,
  renderActions,
  imageFields = [],
  dateFields = [],
  timeFields = [],
  statusFields = [],
  computedFilters = {},
}: DataTableProps<T>) {
  const [searchTerm, setSearchTerm] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(defaultItemsPerPage);

  const getValue = (item: T, key: string): unknown =>
    (item as Record<string, unknown>)[key];

  // Auto-generate columns if not provided
  const columns = providedColumns || (autoColumns ? generateColumns() : []);

  function generateColumns(): Column<T>[] {
    if (data.length === 0) return [];

    const sampleItem = data[0] as Record<string, unknown>;
    const autoGeneratedColumns: Column<T>[] = [];

    Object.keys(sampleItem).forEach((key) => {
      if (excludeColumns.includes(key)) return;

      const value = sampleItem[key];
      const header =
        key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, " $1");

      let column: Column<T> = {
        key,
        header,
        centered: false,
      };

      // Auto-detect column types and apply appropriate rendering
      if (
        imageFields.includes(key) ||
        (typeof value === "string" &&
          value.includes("http") &&
          (value.includes(".jpg") ||
            value.includes(".png") ||
            value.includes(".jpeg")))
      ) {
        column = {
          ...column,
          centered: true,
          mobileHidden: true,
          render: (item) => {
            const imgSrc = getValue(item, key) as string;
            if (!imgSrc)
              return <span className="text-gray-400 text-xs">No image</span>;
            return (
              <Image
                src={imgSrc}
                alt={`${key} image`}
                width={48}
                height={48}
                className="rounded-lg object-cover mx-auto"
              />
            );
          },
        };
      } else if (
        dateFields.includes(key) ||
        (typeof value === "string" && /^\d{4}-\d{2}-\d{2}/.test(value))
      ) {
        column = {
          ...column,
          render: (item) =>
            getValue(item, key)
              ? formatDateForDisplay(getValue(item, key) as string, false)
              : "-",
        };
      } else if (
        timeFields.includes(key) ||
        (typeof value === "string" && /T\d{2}:\d{2}:\d{2}/.test(value))
      ) {
        column = {
          ...column,
          centered: true,
          render: (item) =>
            getValue(item, key)
              ? formatTimeForDisplay(getValue(item, key) as string)
              : "-",
        };
      } else if (
        statusFields.includes(key) ||
        key.toLowerCase().includes("status")
      ) {
        column = {
          ...column,
          centered: true,
          render: (item) => {
            const status = getValue(item, key) as string;
            if (!status) return "-";

            let bgColor = "bg-gray-100 text-gray-800";
            if (
              status.toLowerCase().includes("complete") ||
              status.toLowerCase().includes("active")
            ) {
              bgColor = "bg-green-100 text-green-800";
            } else if (
              status.toLowerCase().includes("progress") ||
              status.toLowerCase().includes("pending")
            ) {
              bgColor = "bg-yellow-100 text-yellow-800";
            } else if (
              status.toLowerCase().includes("inactive") ||
              status.toLowerCase().includes("failed")
            ) {
              bgColor = "bg-red-100 text-red-800";
            }

            return (
              <span
                className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${bgColor}`}
              >
                {status}
              </span>
            );
          },
        };
      } else if (
        key.toLowerCase().includes("department") ||
        key.toLowerCase().includes("position")
      ) {
        column = {
          ...column,
          centered: true,
          render: (item) => {
            const value = getValue(item, key) as string;
            if (!value) return "Unassigned";
            return (
              <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                {value}
              </span>
            );
          },
        };
      } else if (key === "actions" && renderActions) {
        column = {
          ...column,
          centered: true,
          render: renderActions,
        };
      } else if (typeof value === "boolean") {
        column = {
          ...column,
          centered: true,
          render: (item) => (
            <span
              className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                getValue(item, key)
                  ? "bg-green-100 text-green-800"
                  : "bg-red-100 text-red-800"
              }`}
            >
              {getValue(item, key) ? "Yes" : "No"}
            </span>
          ),
        };
      }

      autoGeneratedColumns.push(column);
    });

    return autoGeneratedColumns;
  }

  // Auto-generate search fields if not provided
  const effectiveSearchFields =
    searchFields.length > 0
      ? searchFields
      : data.length > 0
        ? (Object.keys(data[0]).filter(
            (key) =>
              typeof getValue(data[0], key) === "string" &&
              !excludeColumns.includes(key),
          ) as (keyof T)[])
        : [];

  // Filter data based on search and filters
  const filteredData = data.filter((item) => {
    // Search filter
    if (searchable && searchTerm && effectiveSearchFields.length > 0) {
      const searchLower = searchTerm.toLowerCase();
      const matchesSearch = effectiveSearchFields.some((field) => {
        const value = item[field];
        const rawValue = value ? String(value).toLowerCase() : "";

        // Check if there's a corresponding column with a render function
        const column = columns.find(
          (col) => col.key === field || col.key === String(field),
        );
        let renderedValue = "";

        if (column && column.render) {
          try {
            const rendered = column.render(item);
            if (typeof rendered === "string") {
              renderedValue = rendered.toLowerCase();
            } else if (
              rendered &&
              typeof rendered === "object" &&
              "props" in rendered
            ) {
              const extractText = (element: unknown): string => {
                if (typeof element === "string") return element;
                if (typeof element === "number") return String(element);
                if (element && typeof element === "object") {
                  if (
                    "props" in element &&
                    (element as { props?: { children?: unknown } }).props &&
                    (element as { props: { children?: unknown } }).props
                      .children
                  ) {
                    const children = (
                      element as { props: { children: unknown } }
                    ).props.children;
                    if (typeof children === "string") {
                      return children;
                    }
                    if (Array.isArray(children)) {
                      return children.map(extractText).join(" ");
                    }
                    return extractText(children);
                  }
                }
                return "";
              };
              renderedValue = extractText(rendered).toLowerCase();
            }
          } catch {
            renderedValue = rawValue;
          }
        }

        return (
          rawValue.includes(searchLower) || renderedValue.includes(searchLower)
        );
      });
      if (!matchesSearch) return false;
    }

    // Custom filters
    const matchesFilters = filters.every((filter) => {
      if (!filter.value) return true;

      // Check if filter has custom logic
      if (filter.customFilter) {
        return filter.customFilter(item, filter.value);
      }

      // Check if it's a computed filter
      if (computedFilters[filter.key]) {
        const computedValue = computedFilters[filter.key](item);
        return String(computedValue) === filter.value;
      }

      // Default behavior - direct field comparison
      return String(getValue(item, filter.key)) === filter.value;
    });

    return matchesFilters;
  });

  // Auto-generate mobile card if not provided
  const effectiveRenderMobileCard =
    renderMobileCard ||
    ((item: T) => (
      <div className="space-y-2">
        {columns
          .filter((col) => !col.mobileHidden)
          .map((column) => (
            <div key={column.key} className="flex justify-between">
              <span className="text-sm font-medium text-gray-500">
                {column.header}:
              </span>
              <span className="text-sm text-gray-900">
                {column.render
                  ? column.render(item)
                  : String(getValue(item, column.key) || "-")}
              </span>
            </div>
          ))}
      </div>
    ));

  // Pagination calculations
  const totalPages = Math.ceil(filteredData.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const paginatedData = filteredData.slice(startIndex, endIndex);

  // Reset to first page when filters change
  useEffect(() => {
    setCurrentPage(1);
  }, [searchTerm, filters]);

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
  };

  const handleItemsPerPageChange = (newItemsPerPage: number) => {
    setItemsPerPage(newItemsPerPage);
    setCurrentPage(1);
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center py-8">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        <span className="ml-2 text-gray-600">Loading...</span>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Search and Filters */}
      {(searchable || filters.length > 0) && (
        <div className="bg-gray-50 p-4 rounded-lg">
          <div
            className={`grid gap-4 ${
              filters.length === 0
                ? "grid-cols-1"
                : `grid-cols-1 md:grid-cols-2 lg:grid-cols-${Math.min(
                    filters.length + 1,
                    4,
                  )}`
            }`}
          >
            {searchable && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Search
                </label>
                <input
                  type="text"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                  placeholder={searchPlaceholder}
                />
              </div>
            )}
            {filters.map((filter) => (
              <div key={filter.key}>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  {filter.label}
                </label>
                <select
                  value={filter.value}
                  onChange={(e) => filter.onChange(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                >
                  {filter.options.map((option) => (
                    <option key={option.value} value={option.value}>
                      {option.label}
                    </option>
                  ))}
                </select>
              </div>
            ))}
          </div>

          {/* Results Info and Items Per Page */}
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center space-y-2 sm:space-y-0 mt-4">
            <div className="text-sm text-gray-600">
              Showing {startIndex + 1} to{" "}
              {Math.min(endIndex, filteredData.length)} of {filteredData.length}{" "}
              items
            </div>
            <div className="flex items-center space-x-2">
              <label className="text-sm text-gray-600">Show:</label>
              <select
                value={itemsPerPage}
                onChange={(e) =>
                  handleItemsPerPageChange(Number(e.target.value))
                }
                className="px-2 py-1 border border-gray-300 rounded text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              >
                {itemsPerPageOptions.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
              <span className="text-sm text-gray-600">per page</span>
            </div>
          </div>
        </div>
      )}

      {/* Desktop Table */}
      <div className="hidden md:block bg-white border border-gray-200 rounded-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                {columns.map((column) => (
                  <th
                    key={column.key}
                    className={`px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider ${
                      column.centered ? "text-center" : "text-left"
                    }`}
                  >
                    {column.header}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {paginatedData.map((item, index) => (
                <tr
                  key={(getValue(item, "id") as string | number) || index}
                  className={`hover:bg-gray-50 ${
                    onRowClick ? "cursor-pointer" : ""
                  }`}
                  onClick={() => onRowClick?.(item)}
                >
                  {columns.map((column) => (
                    <td
                      key={column.key}
                      className={`px-4 py-4 text-sm max-w-xs ${
                        column.centered ? "text-center" : "text-left"
                      }`}
                    >
                      <div
                        className={`${column.render ? "" : "truncate"} ${
                          column.centered ? "flex justify-center" : ""
                        }`}
                      >
                        {column.render ? (
                          <div className="w-full">{column.render(item)}</div>
                        ) : (
                          <span
                            className="truncate block"
                            title={String(getValue(item, column.key) || "-")}
                          >
                            {String(getValue(item, column.key) || "-")}
                          </span>
                        )}
                      </div>
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Mobile Cards */}
      <div className="md:hidden space-y-4">
        {paginatedData.map((item, index) => (
          <div
            key={(getValue(item, "id") as string | number) || index}
            className={`bg-white border border-gray-200 rounded-lg p-4 shadow-sm hover:shadow-md transition-shadow ${
              onRowClick ? "cursor-pointer" : ""
            }`}
            onClick={() => onRowClick?.(item)}
          >
            {renderMobileCard
              ? renderMobileCard(item)
              : effectiveRenderMobileCard(item)}
          </div>
        ))}
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex flex-col sm:flex-row justify-between items-center space-y-4 sm:space-y-0">
          <div className="text-sm text-gray-600">
            Page {currentPage} of {totalPages}
          </div>
          <div className="flex items-center space-x-2">
            <button
              onClick={() => handlePageChange(currentPage - 1)}
              disabled={currentPage === 1}
              className="px-3 py-2 text-sm border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Previous
            </button>
            <div className="flex items-center space-x-1">
              {(() => {
                const pages = [];
                const showEllipsis = totalPages > 7;
                if (!showEllipsis) {
                  for (let i = 1; i <= totalPages; i++) {
                    pages.push(
                      <button
                        key={i}
                        onClick={() => handlePageChange(i)}
                        className={`px-3 py-2 text-sm border rounded-md ${
                          currentPage === i
                            ? "bg-blue-600 text-white border-blue-600"
                            : "border-gray-300 hover:bg-gray-50"
                        }`}
                      >
                        {i}
                      </button>,
                    );
                  }
                } else {
                  pages.push(
                    <button
                      key={1}
                      onClick={() => handlePageChange(1)}
                      className={`px-3 py-2 text-sm border rounded-md ${
                        currentPage === 1
                          ? "bg-blue-600 text-white border-blue-600"
                          : "border-gray-300 hover:bg-gray-50"
                      }`}
                    >
                      1
                    </button>,
                  );
                  if (currentPage > 3) {
                    pages.push(
                      <span key="ellipsis1" className="px-2 text-gray-500">
                        ...
                      </span>,
                    );
                  }
                  const start = Math.max(2, currentPage - 1);
                  const end = Math.min(totalPages - 1, currentPage + 1);
                  for (let i = start; i <= end; i++) {
                    if (i !== 1 && i !== totalPages) {
                      pages.push(
                        <button
                          key={i}
                          onClick={() => handlePageChange(i)}
                          className={`px-3 py-2 text-sm border rounded-md ${
                            currentPage === i
                              ? "bg-blue-600 text-white border-blue-600"
                              : "border-gray-300 hover:bg-gray-50"
                          }`}
                        >
                          {i}
                        </button>,
                      );
                    }
                  }
                  if (currentPage < totalPages - 2) {
                    pages.push(
                      <span key="ellipsis2" className="px-2 text-gray-500">
                        ...
                      </span>,
                    );
                  }
                  if (totalPages > 1) {
                    pages.push(
                      <button
                        key={totalPages}
                        onClick={() => handlePageChange(totalPages)}
                        className={`px-3 py-2 text-sm border rounded-md ${
                          currentPage === totalPages
                            ? "bg-blue-600 text-white border-blue-600"
                            : "border-gray-300 hover:bg-gray-50"
                        }`}
                      >
                        {totalPages}
                      </button>,
                    );
                  }
                }
                return pages;
              })()}
            </div>
            <button
              onClick={() => handlePageChange(currentPage + 1)}
              disabled={currentPage === totalPages}
              className="px-3 py-2 text-sm border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Next
            </button>
          </div>
        </div>
      )}

      {/* Empty State */}
      {filteredData.length === 0 && (
        <div className="text-center py-8">
          <p className="text-gray-500">{emptyMessage}</p>
        </div>
      )}
    </div>
  );
}
